# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extendMatrix <- function(mat, h) {
    .Call('_hicrep_extendMatrix', PACKAGE = 'hicrep', mat, h)
}

estimateLengthOrWidth <- function(x, nrow, h) {
    .Call('_hicrep_estimateLengthOrWidth', PACKAGE = 'hicrep', x, nrow, h)
}

fastMeanFilter <- function(mat, h) {
    .Call('_hicrep_fastMeanFilter', PACKAGE = 'hicrep', mat, h)
}

